### ISSUE TITLE
SlapSegIII::Validation::readFile bug

### ISSUE THREAD

**Issue by msquillante** [usnistgov/slapseg#1]
Trying to test with my own dataset, I've found this bug, still present in the new release.

In file slapseg-master/slapsegiii/validation/src/slapsegiii_validation.cpp
SlapSegIII::Validation::readFile doesn't read the entire file content

needed to add:
`
 file >> std::noskipws;
`

**Comment by gfiumara** [comment]
Thanks. You are correct that it could cause issues with some data, though it does not with the [official validation data](https://pages.nist.gov/slapseg/doc/slapsegiii/validation_dataset_agreement.pdf). I'll make the change shortly.
